[font]
size = 10.0

[font.bold]
family = "Terminess Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Terminess Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Terminess Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Terminess Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.8


#import = ["~/.config/alacritty/themes/themes/everforest_dark.toml"]

# Colors (Everforest Dark)

# Default colors
[colors]
  [colors.primary]
    background = '#161e29'
    foreground = '#85a7d6'


  [colors.normal]
    black   = '#192330'
    red     = '#c25872'
    green   = '#81b29a'
    yellow  = '#dbad3f'
    blue    = '#719cd6'
    magenta = '#9977cf'
    cyan    = '#5e8d87'
    white   = '#57616f'

  [colors.bright]
    black   = '#283648'
    red     = '#c9607a'
    green   = '#97beab'
    yellow  = '#dbc380'
    blue    = '#85a7d6'
    magenta = '#a789d6'
    cyan    = '#8abeb7'
    white   = '#d4d9e1'
