[font]
size = 10.0

[font.bold]
family = "Terminess Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Terminess Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Terminess Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Terminess Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.8

# Default colors
[colors]

  # Colores predeterminados
  [colors.primary]
    background = "#161e29"
    foreground = "#73a9de"

  # Colores normales
  [colors.normal]
    black 	= "#192330"
    red 	= "#c94f6d"
    green 	= "#81b29a"
    yellow 	= "#dbc074"
    blue 	= "#719cd6"
    magenta = "#9d79d6"
    cyan 	= "#9bc9b3"
    white 	= "#57616f"

  # Colores brillantes
  [colors.bright]
    black 	= "#283648"
    red 	= "#c9607a"
    green 	= "#97beab"
    yellow 	= "#dbc380"
    blue 	= "#85a7d6"
    magenta = "#a789d6"
    cyan 	= "#8abeb7"
    white 	= "#d4d9e1"